spring:
  application:
    name: graphql-course-demo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /subscriptions

  threads:
    virtual:
      enabled: true

  jwks:
    uri: http://localhost:8099/oauth2/jwks

populate:
  table:
    enabled: false