spring:
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://${HOST}:${PORT}/${DB_NAME}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}

  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /subscriptions

  threads:
    virtual:
      enabled: ${ENABLE_VIRTUAL_THREAD}

  jwks:
    uri: http://${AUTH_HOST}:8099/oauth2/jwks

populate:
  table:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSED_ENDPOINTS:health}

  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true