spring:
  application:
    name: graphql-course-demo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enabled: true

populate:
  table:
    enabled: false