spring:
  application:
    name: graphql-course-demo

  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /subscriptions

  threads:
    virtual:
      enabled: true

  profiles:
    active: test

  jwks:
    uri: http://localhost:8099/oauth2/jwks