name: build push image for deployment
on:
  push:
    branches:
      - main

jobs:
  build-job-section:
    environment: docker
    runs-on: ubuntu-latest

    container: postgres
    services:
      postgres:
        image: 'postgres:16.2'
        env:
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_USER: ${{ secrets.USERNAME }}
        ports:
          - 5432:5432

    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK GraalVm 22
        run: |
          apt-get update -y &&  apt-get upgrade -y && apt-get install wget -y \
          && wget https://download.oracle.com/graalvm/22/archive/graalvm-jdk-22.0.1_linux-x64_bin.tar.gz \
          && wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
          && tar -xf graalvm-jdk-*_bin.tar.gz \
          && tar -xf apache-maven-3.9.9-bin.tar.gz \
          && pwd && ls \
          && rm graalvm-*.tar.gz && rm apache-maven-3.9.9-bin.tar.gz \
          && echo 'export JAVA_HOME=graalvm-jdk-22.0.1+8.1' >> ~/.bashrc \
          && echo 'export MAVEN_HOME=apache-maven-3.9.9' >> ~/.bashrc \
#          && echo 'export PATH=apache-maven-3.9.9/bin:graalvm-jdk-22.0.1+8.1/bin:$PATH' >> ~/.bashrc \
          && source ~/.bashrc \
          && cat ~/.bashrc
          

      - name: prepare for graalvm
        run: apt-get install -y build-essential zlib1g-dev

      - name: Build with maven
        run: mvn clean -Pnative native:compile -DskipTests -Dparallel=all -DperCoreThreadCount=true -Duser.timezone=Africa/Lagos -Djava.security.egd=file:/dev/./urandom -Dspring-boot.run.profiles=${{ vars.SPRING_PROFILE }}
      - name: list files
        run: ls target/**

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: graphql-demo-artifact
          path: |
            target/graphql-course-demo
            Dockerfile
          overwrite: 'true'
          retention-days: 5

  push-image-section:
    environment: action
    needs: build-job-section
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: graphql-demo-artifact

      - name: Output downloaded contents
        run: ls && ls target/**

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password:  ${{ secrets.DOCKER_PASSWORD }}

      - name: push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gdemo:1.0
          context: .